### ISSUE TITLE
Wrong hyphen added in front of file path

### ISSUE THREAD

**Issue by ghost** [marc136/node-folder-hash#137]
I was testing this with the folder of electron inside node_modules and unfortunately it somehow oddly adds a hyphen in front of a path and then fails to find the file and crashes.

I don't know why it's adding that hyphen but it clearly shouldn't.

If you install electrons latest version (17.1.2 as of now) and try this, you will be able to reproduce it.

**Comment by marc136** [comment]
Hello @infosisio, unfortunately I was not able to reproduce your issue.

I created a new folder, ran `npm init -y` and then `npm install --save folder-hash electron`. After that hashing both `'node_modules/electron'` and `'node_modules'` worked for me without problems.

```js
const { hashElement } = require('folder-hash');
const options = {};
hashElement('node_modules/electron', options)
  .then(hash => {
    console.log(hash.toString());
  })
  .catch(error => {
    return console.error('hashing failed:', error);
  });
```

Can you try if you have the same issue when running `npm install` in the attached folder?
[issue-137.zip](https://github.com/marc136/node-folder-hash/files/8240472/issue-137.zip)

Apart from that:
Can you give me more information? Like OS? Or are you maybe using pnpm to install the dependencies? Because pnpm creates symlinks in your node_modules folder, and I only tested the symlink behavior on linux.

If symlinks are involved, you could also try to set the [symlink option `ignoreTargetContentAfterError: true`](https://github.com/marc136/node-folder-hash#symlink-options) to ignore errors (and skip hashing files).

**Comment by infosisio** [comment]
@marc136 Hello, that's strange, trying your example, I don't get that error. I am still getting it on the program I mentioned earlier though. I am on Ubuntu 20.04.

**Comment by marc136** [comment]
Did you try to `rm -rf node_modules` and install all dependencies fresh with `npm install`?

If the error persists, you could try to remove packages (or start from a clean install and start adding packages).

If you have a lot of dependencies, you could maybe try to remove first the modules that are linked into your folder and remove those first. The command `find node_modules -path node_modules/.bin -prune -o -type l` (adapted from [this so answer](https://stackoverflow.com/a/4210072)) might help you.
